### ISSUE TITLE
Gacha Placer OnPersistentLoad patch ignores manual mode

### ISSUE THREAD

**Issue by Fizzyhex** [Lakatrazz/BONELAB-Fusion#101]
[the patch in question](https://github.com/Lakatrazz/BONELAB-Fusion/blob/9e2be403cc689598548fcf3e862d02e3781336d9/LabFusion/src/Patching/Patches/Props/GachaPlacerPatches.cs#L19)

Right now gachas will spawn all the time even if manual mode is off, can lead to some weird issues.

**Comment by Lakatrazz** [comment]
Fixed in 368102d
