### ISSUE TITLE
Fusion Crashes BONELAB on Quest with LemonLoader 0.6.5

### ISSUE THREAD

**Issue by Mosnar23** [Lakatrazz/BONELAB-Fusion#102]
Now that LemonLoader 0.6.5 is officially out, I installed it on my friend's copy of BONELAB, but when I tried to install Fusion, the game would not stop crashing. BoneLib functions perfectly, so it can't be that. I mentioned it to some of the people in the LemonLoader Discord server, and they said that Fusion would need to be updated.

**Comment by Lakatrazz** [comment]
Fusion does not support quest currently, please wait for the next update

**Comment by DarkCat736** [comment]
Is there an ETA for the next update?

**Comment by Mosnar23** [comment]
> Fusion does not support quest currently, please wait for the next update

I mean, yea, Ik, just making sure that you knew that it didn't work.

**Comment by Lakatrazz** [comment]
Fixed in b0ac930

**Comment by Mosnar23** [comment]
Yippee!
