### ISSUE TITLE
Fusion not working on Oculus

### ISSUE THREAD

**Issue by zaynethedev** [Lakatrazz/BONELAB-Fusion#104]
I know that you made the fixes but please build it into a dll. I've been trying for hours and it is NOT working.

**Comment by DarkCat736** [comment]
Yes, please make a compiled release!

**Comment by Lakatrazz** [comment]
The update is not done. Wait for release.

**Comment by DarkCat736** [comment]
> The update is not done. Wait for release.

Ok, thanks for your work
