### ISSUE TITLE
No networking layer

### ISSUE THREAD

**Issue by Hedrixz** [Lakatrazz/BONELAB-Fusion#11]
I own the game on steam and Steam_VR is selected, yet the mod insists that steam is not open. When I open the game, this shows up in console aswell:

Initialized mod with an empty networking layer!
[01:06:49.994] [LabFusion] This usually means all other network layers failed to initialize, or you selected Empty in the settings.

I've never gotten this mod to work and I've seen countless others in the discord having the same issue, but noone ever replies.

**Comment by Tw1kShow** [comment]
I have the same problem and I can't solve it 😭

**Comment by Lakatrazz** [comment]
This has been fixed in hotfix 1.3.2
