### ISSUE TITLE
Bonelab Quest LemonLoader Update?

### ISSUE THREAD

**Issue by YezTez** [Lakatrazz/BONELAB-Fusion#112]
I was just wondering if or if not the update for lemonloader 0.6.5 or .6.6 is coming out or if its even in progression? Me and my friend are  a big fan of bonelab and weve been wanting to play multiplayer for a while but I only got it once patch 6 came out, I completed the campaign and then got a bunch of mods and once I went to get the multiplayer mod for my quest it said lemonloader 0.6.5 support not available yet and this really made me upset.

**Comment by Lakatrazz** [comment]
Next fusion update supports quest
