### ISSUE TITLE
Where does fusion store mods it's downloaded?

### ISSUE THREAD

**Issue by winkstinks** [Lakatrazz/BONELAB-Fusion#113]
I joined a random fusion lobby after a couple of months of not playing, and it was enabled to keep downloaded mods. I want to delete the mods it downloaded, where do I go?

**Comment by Lakatrazz** [comment]
Kept mods are downloaded to the regular bonelab mods folder in appdata.
In the future for questions, use the discord server, not github issues.

**Comment by winkstinks** [comment]
ok, thank you sir. i will keep that in mind.
