### ISSUE TITLE
Negative damage causes blood splatters

### ISSUE THREAD

**Issue by spellboundtriangle** [Lakatrazz/BONELAB-Fusion#117]
I have an SDK mod that deals negative damage (healing) with a VoidLogic Damage Volume. This results in blood effects when being used in Fusion.

https://github.com/user-attachments/assets/4cc22ef6-6f29-44ff-b691-996ba13a1657

![image](https://github.com/user-attachments/assets/5a26bef6-241f-41e3-921d-2d6ea19680da)

I'm unsure if this is due to the game's implementations or not (or if it's because I have bad setup in the mod), if it is then feel free to close this issue.

**Comment by Lakatrazz** [comment]
This is just how impact properties deals with negative damage in the base game, I can't really do much about it afaik
