### ISSUE TITLE
Prioritize gun mods

### ISSUE THREAD

**Issue by BunderBoats** [Lakatrazz/BONELAB-Fusion#119]
avatar and ncps do not change gameplay much. With unloaded gun mods you can seem to die for no reason which is very irritating especially with gamemodes like deathmatch.

**Comment by Lakatrazz** [comment]
What exactly is being requested here?

**Comment by FlutterCat555** [comment]
> What exactly is being requested here?

make gun mods download over all other mods (have priority)

**Comment by Lakatrazz** [comment]
I will not be doing this, I cannot detect what type of spawnable a spawnable is when it's being downloaded, plus mods can contain more than just guns or avatars, they can contain multiple types of mods in one pallet
