### ISSUE TITLE
"requesting lobby ids took to long" on q2 patch 6

### ISSUE THREAD

**Issue by Noob-A** [Lakatrazz/BONELAB-Fusion#123]
I see "requesting lobby ids took to long" on my oculus quest 2
Fusion version: 1.9.3
Fusion helper version: 1.1.3
Patch 6

<img width="831" alt="image" src="https://github.com/user-attachments/assets/e550516e-7a24-4d29-af17-52dd0a23b70c" />
<img width="393" alt="image" src="https://github.com/user-attachments/assets/44e06aad-3dea-4c6c-b037-69d1bbc5008d" />

**Comment by sors-code** [comment]
How'd you fix this? I have this issue and have been aired on issues
