### ISSUE TITLE
"Disconnected from current lobby"

### ISSUE THREAD

**Issue by MatthewTardis168** [Lakatrazz/BONELAB-Fusion#14]
this isn't an issue with me but a friend of mine. it was perfectly working a few days ago, then it just fails to let him connect. I have no idea whats going on. he tried to reinstall bonelib, fusion, and melon loader and it still fails. now hes reinstalling bonelabs.
[MelonLoader_23-04-24_01-36-41.639.log](https://github.com/Lakatrazz/BONELAB-Fusion/files/11305094/MelonLoader_23-04-24_01-36-41.639.log)

**Comment by embedvr** [comment]
what was the fix?
