### ISSUE TITLE
Objects and events not syncing correctly and grip inconsistent

### ISSUE THREAD

**Issue by RipcordTheWicker** [Lakatrazz/BONELAB-Fusion#20]
Tried to find a Discord for this mod, couldn't find one, so my only option is to post here. I made a GitHub account purely for this.

Syncing across clients for me and my friend is really, really inconsistent. Arena doesn't sync enemies or guns, and we will often completely lose our ability to grip objects, guns, etc, in one or both hands. I'm not sure what I'm doing wrong (if anything), and would appreciate some feedback/support.

**Comment by Checkerb0ard** [comment]
Check if you have updated the mod recently (arena sync was iffy on early versions) here is the discord, https://discord.gg/FmRGBgbc3N

**Comment by RipcordTheWicker** [comment]
Thanks very much for the Discord! As far as I'm aware, I'm on the latest version of the public beta of BoneLab, version 0.5.7 of MelonLoader, and the latest version of BoneLab Fusion

**Comment by Lakatrazz** [comment]
Fixed in discord, the issue was Fusion Autodownloader
