### ISSUE TITLE
Add API for fusion sdk to fetch voice activity

### ISSUE THREAD

**Issue by Meister1593** [Lakatrazz/BONELAB-Fusion#21]
I noticed that in this https://github.com/Lakatrazz/BONELAB-Fusion/commit/e1c03ee8c8690e74c42913350d2d41dd08559bd3 commit (https://github.com/Lakatrazz/BONELAB-Fusion/blob/e1c03ee8c8690e74c42913350d2d41dd08559bd3/Core/src/Network/Helpers/VoiceHelper.cs file) there is added api for voice enabled, deafened, etc but theres no mention of actual voice activity.
Can it be added so in case someone makes a voice indicator fusion extension, it could show if whenever voice is actually active or not?
I guess it could be either made as an boolean, or as an event of whenever it's changing state from/when active/inactive

**Comment by Lakatrazz** [comment]
I'll implement this when I switch to unity's microphone API

**Comment by Lakatrazz** [comment]
This is now implemented in the [microphone rewrite branch](https://github.com/Lakatrazz/BONELAB-Fusion/tree/microphone-rewrite) as HasVoiceActivity and VoiceAmplitude
