### ISSUE TITLE
fusion keeps disconnecting me

### ISSUE THREAD

**Issue by PedroViniVince** [Lakatrazz/BONELAB-Fusion#28]
after 3 - 5 minutes fusion disconnects me from the server

[PCVR Streaming Method: ALVR]
[Game Version: 1.5.0 (Patch 3)]

**Comment by Lakatrazz** [comment]
This is caused by you losing connection to the server and Steam automatically disconnecting you.

**Comment by PedroViniVince** [comment]
thanks lakatrazz
i think i will switch to the spacewar connection now.
