### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by N0BL3US3R** [Lakatrazz/BONELAB-Fusion#30]
After finding the server and loading into bonelab, on the first few frames of the playable state of bonelab (Main menu) it instantly crashes. I dont know what to really do but Idk cuz im new to this stuff

**Comment by spellboundtriangle** [comment]
Can you verify that you removed v0.1.1 of the LemonLoader installer, installed v0.2.0 of the LemonLoader installer, and used that to patch an unpatched version of the BONELAB public beta?

**Comment by N0BL3US3R** [comment]
I just realized that lemon loader got an update earlier
