### ISSUE TITLE
Crashes quest 2

### ISSUE THREAD

**Issue by Alfieyonk** [Lakatrazz/BONELAB-Fusion#31]
So the new update 1.5 I tried to get it to work it worked originally when I did it but now the won't load it crashes after like 30cseconds on quest 2 standalone the updater is not installed as suggested but no work

**Comment by Alfieyonk** [comment]
Also the bit thingy in void g114 does not exist just normal void with the oatch 3 stuff and I'm on lemonloader v2 or whatever the newest one is help

**Comment by Alfieyonk** [comment]
Also is there a way you can make it so more networking layers are available on mac since the one used for Mac has no public lobbys but are you able to join Public lobbies kn quest since I have no Friends

**Comment by Lakatrazz** [comment]
The one used for map has like 20 public lobbies constantly. The crashing is caused by you not repatching bonelab when installing the new lemonloader update, or installing it incorrectly.
