### ISSUE TITLE
No vending machines :(

### ISSUE THREAD

**Issue by enderloch** [Lakatrazz/BONELAB-Fusion#33]
I loaded the game after following a yt guide added yesterday, for quest 2 using fusionhelper. None of the machines showed up, so I played till I got into the lab part of the game. I will try restarting.

**Comment by Goggogagga** [comment]
I think you have to complete the game to get to Void G114 and the machines should be there.
If you dont want to complete the game you can download a 100% save file from a website like mod.io and replace the save file you have with the one you downloaded.
Just connect your headset to your computer and open sidequest press the folder icon upp in the top right corner and go to android/data/com.stresslevelzero.bonelab/files/saves and replace the .json file in the saves folder with the .json file you downloaded

**Comment by Idkbythispoint** [comment]
This should be closed.
