### ISSUE TITLE
Win Arm

### ISSUE THREAD

**Issue by jamersb** [Lakatrazz/BONELAB-Fusion#34]
Hi, 

Just wondering if anyone knows why this is happening?
I'm watching a tut rn and it says to download FusionHelper_win_armx64.zip, but that isnt there, the only one that is there is FusionHelper_win_x64.zip?

**Comment by VollKEK** [comment]
there is one called "FusionHelper_mac_arm64.zip", but that is obviously for mac, so just stick to "FusionHelper_win_x64.zip" (if ur on windows)
