### ISSUE TITLE
mic not working :/

### ISSUE THREAD

**Issue by VollKEK** [Lakatrazz/BONELAB-Fusion#37]
im on the quest 2 and fusion runs smoothly with some mods.
i looked in the vc settings and made sure that the server has vc enabled but its just not working, it works in other games.
i think whats happening is that the input isnt getting sent to fusion helper for it to get output for the players.
I can hear other people and when i tried talking to somebody or asking if my mic works nobody replied.

**Comment by TrevTV** [comment]
Quest 2 does not have VC support as of right now
