### ISSUE TITLE
Add support for custom win/lose/tie gamemode themes to Marrow SDK Integration

### ISSUE THREAD

**Issue by spellboundtriangle** [Lakatrazz/BONELAB-Fusion#38]
The Fusion Marrow SDK Integration supports playing up to four different songs during gamemode rounds, and allows you to have a different set for each three of the base gamemodes. However, it does not allow you to change the win/lose/tie themes that are played at the end of the round, as far as I can tell.

It would be great if you could set these to custom audio tracks in custom levels with DM support with specific themes or are based on other games that may have apt music for it.

**Comment by XD2525** [comment]
fr

**Comment by Lakatrazz** [comment]
Fusion SDK now supports more than 4 songs as well as Victory, Failure, and Tie song overrides
