### ISSUE TITLE
Stuck in a squat

### ISSUE THREAD

**Issue by scaverYT** [Lakatrazz/BONELAB-Fusion#4]
Im on the oculus pcvr and just installed everything and switched my version to the public beta. I launched the game and was stuck in squat where I cant move.

**Comment by DINOTICK-Dev** [comment]
I'm pretty sure the mod requires Steam PCVR for networking, meaning no Oculus app, and you have to set your version to the public_beta branch... Are you sure you are on the right branch? Perhaps send some screenshots.

**Comment by scaverYT** [comment]
![Oculus 3_17_2023 8_46_10 AM](https://user-images.githubusercontent.com/128110624/225923073-150c9a46-03bc-4a8e-82e9-4957a817b37c.png)

**Comment by scaverYT** [comment]
![stress-level-zero-inc-bonelab 3_17_2023 8_48_58 AM](https://user-images.githubusercontent.com/128110624/225923686-041de1b8-ed0d-4232-b145-fc5642a0e5f9.png)

**Comment by scaverYT** [comment]
![stress-level-zero-inc-bonelab 3_17_2023 8_49_04 AM](https://user-images.githubusercontent.com/128110624/225923726-c7b829b2-71d1-44f3-b0bf-0f8e967726f6.png)
![stress-level-zero-inc-bonelab 3_17_2023 8_49_12 AM](https://user-images.githubusercontent.com/128110624/225923755-b9ce3927-f9cb-4b8a-a3e3-123c1cb91d64.png)

**Comment by DINOTICK-Dev** [comment]
I sort of meant... In game. Is it ok if you could do that for me? Thanks!

**Comment by scaverYT** [comment]
I uninstalled, reinstalled, updated to live. Reinstalled as public beta, and was good to go. Thanks

**Comment by DINOTICK-Dev** [comment]
Cool, @Lakatrazz, please close this as I currently do not possess the ability to close the issue myself.

**Comment by TarekLP** [comment]
So is it fixed or do i have to reinstall as live then public
