### ISSUE TITLE
BoneLab keeps freezing

### ISSUE THREAD

**Issue by derpguywazhere** [Lakatrazz/BONELAB-Fusion#53]
I'm on Quest 2, I installed Fusion and when I booted up Bonelab, and When it was done loading it freeze of Crashed. I also Heard Some Music That was NOT the BodyMall music. Anyone Help me?

**Comment by SilliestDinosaur** [comment]
Okay so the music you heard was probably the "BitMart" which is this cosmetics shop for fusion, what version of BONELAB are you on? (Patch 3, Patch 2, etc)

**Comment by derpguywazhere** [comment]
> Okay so the music you heard was probably the "BitMart" which is this cosmetics shop for fusion, what version of BONELAB are you on? (Patch 3, Patch 2, etc)

I think Patch 3
