### ISSUE TITLE
Respawn at death location | Feature request

### ISSUE THREAD

**Issue by Virus-vr** [Lakatrazz/BONELAB-Fusion#60]
For some maps and gameplay styles it would be welcome if you could respawn where you died instead of the spawn.
It would save you some time walking/flying back to the action.

**Comment by Virus-vr** [comment]
I tried to add the "Enchantment / Feature request" label but it seams I can't add them myself.

**Comment by KitchenBoy08** [comment]
What would be the point of death, then? Just turn off mortality in the Server settings

**Comment by capybarajtmc** [comment]
> What would be the point of death, then? Just turn off mortality in the Server settings

I see OP's request. People film skits in bonelab and it involves killing other people most of the time. This can help if the items also drop when dead. It can also probably be used for other features I'm just not sure

**Comment by Virus-vr** [comment]
> What would be the point of death, then? Just turn off mortality in the Server settings

capybarajtmc gave a good example of where it would be useful.
Also you would still be temporarily be knocked out / ragdoll, so it would not be the same as turning mortality off.
If you're playing around with your friends on a huge map and you die you don't want to fly all the way back to where you where. If you turn mortality off you might not even know that you where shot/punched. It just feels unresponsive that way.

**Comment by KitchenBoy08** [comment]
I guess a better way for this to work is to have an Enumerable setting where you can switch between "Mortal", "Immortal" and "Knockout" where if youre knocked out you just ragdoll for a moment and get back up :shrug:

Might PR that if I get to it lol

**Comment by KitchenBoy08** [comment]
pretty sure lak saw this lol

**Comment by Lakatrazz** [comment]
Added in 389c117
