### ISSUE TITLE
Players can die upon getting hit with melee damage

### ISSUE THREAD

**Issue by adamd3v** [Lakatrazz/BONELAB-Fusion#7]
In very certain circumstances, players can die instantly when being dealt small damage by either gun butts, blunt/sharp weapons, or punches.

**Comment by DINOTICK-Dev** [comment]
This may be because of the amount of damage melee weapons simply cause, however, I have been thinking about going about myself and making a balancing mod or pull request.

**Comment by Lakatrazz** [comment]
This was caused by the bhaptics integration mod and not Fusion
