### ISSUE TITLE
Project won't build with/without dependencies. Can anybody help?

### ISSUE THREAD

**Issue by crimsonclientonotp** [Lakatrazz/BONELAB-Fusion#72]
![image](https://github.com/user-attachments/assets/8ca30a10-59b9-490b-bb7c-f63a8ab5cae2)

**Comment by crimsonclientonotp** [comment]
@Lakatrazz  Do you know why this is happening??

**Comment by Lakatrazz** [comment]
You don't have the latest BoneLib version. Also, if you're building this to play, I do not recommend it, as it is an unstable development version which also doesn't work on patch 5 yet.

**Comment by crimsonclientonotp** [comment]
> You don't have the latest BoneLib version. Also, if you're building this to play, I do not recommend it, as it is an unstable development version which also doesn't work on patch 5 yet.

Thanks for the response. I'll wait for the real version of fusion to come out.

**Comment by Lakatrazz** [comment]
You're using the wrong branch of BoneLib. The correct one is the ml-new branch on adamdev's github
