### ISSUE TITLE
Patch 5

### ISSUE THREAD

**Issue by vadimsman** [Lakatrazz/BONELAB-Fusion#73]
Will you make an update for the 5th patch?

**Comment by capybarajtmc** [comment]
No, he's actually quitting modding forever (delete this vro 🙏🙏)

**Comment by vadimsman** [comment]
Is there any way to run Fusion in patch 5?

**Comment by vadimsman** [comment]
I'm sorry if my English is bad (I use a translator)

**Comment by capybarajtmc** [comment]
Who's gonna tell them

**Comment by Lakatrazz** [comment]
Already on patch 5, just not released

**Comment by Mosnar23** [comment]
wdym, is there a commit and you haven't been releasing the updates, or are we supposed to use the unofficial BoneLib Patch 5? ([https://thunderstore.io/c/bonelab/p/funny_people/BoneLib_Patch_5_Unofficial/](url))
