### ISSUE TITLE
Game Freezing

### ISSUE THREAD

**Issue by crimsonclientonotp** [Lakatrazz/BONELAB-Fusion#76]
After playing in a server for around 5 minutes, the game just freezes, and you cant move anything at all and everything is unloaded. After a minute of it happening, its stops, but continues to happen. I don't know whats causing this. Hoping a fix for this comes soon.

**Comment by Lakatrazz** [comment]
Give more information. What version of fusion? Reproduction steps? Log file?

**Comment by crimsonclientonotp** [comment]
Newest version. The game doesnt crash. I can talk, and hear but the game just freezes in time and most items and object despawn. After like 1-2 minutes the items respawn and I can move freely. I'll check the log file and give more info.

**Comment by crimsonclientonotp** [comment]
[24-7-26_19-29-11.log](https://github.com/user-attachments/files/16401208/24-7-26_19-29-11.log)
Got it. You can look in to it. I'm not so good at coding, and reading logs and stuff.

**Comment by Lakatrazz** [comment]
I see, you are on an unreleased development version. This version also appears to be very old, which explains your issues.

**Comment by Lakatrazz** [comment]
Please wait for an official release.

**Comment by crimsonclientonotp** [comment]
Alright thanks.
