### ISSUE TITLE
heres why i uploaded to thunderstore.

### ISSUE THREAD

**Issue by crimsonteamthunderstore** [Lakatrazz/BONELAB-Fusion#78]
![image](https://github.com/user-attachments/assets/f5c91321-7477-4bb3-b5f5-0f33c4e9e224)
![image](https://github.com/user-attachments/assets/b57d9e49-ee2e-452a-ad8f-756176b32ddf)
heres the proof im crimsonteam. yes i uploaded both mods to thunderstore so people dont take time to compile the github project and download stuff. i just made it so people can download it easily, and faster then compiling. im sorry if i made you mad or annoyed. i will not take credit for any mods i upload. i will link your kofi link in the upload later tomorrow or later midnight. once you upload fusion im deleting my upload. same with the mag perception upload i did.

**Comment by Lakatrazz** [comment]
Please stop reuploading people's mods. I speak on behalf of most code modders that we'd rather them not be uploaded until finished, especially ones without licenses permitting that, and without permission being asked in the first place. I don't care whether or not you link my kofi, just dont upload them. If you want people to be able to play patch 5 fusion or mag perception or whatever, then link them the github, or send them the file yourself. There is a reason that your uploads have been taken down multiple times and a reason that these versions are not currently on thunderstore.

**Comment by extraes** [comment]
you annoying as hell and the reason im hesitant on open sourcing mods

**Comment by ProjectCrytos** [comment]
> ![image](https://private-user-images.githubusercontent.com/177441854/354877084-f5c91321-7477-4bb3-b5f5-0f33c4e9e224.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NDg1OTgsIm5iZiI6MTcyMjc0ODI5OCwicGF0aCI6Ii8xNzc0NDE4NTQvMzU0ODc3MDg0LWY1YzkxMzIxLTc0NzctNGJiMy1iNWY1LTBmMzNjNGU5ZTIyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQwNTExMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTY4ODI0NzMyMjgyMDdmZTgyMWRmODI5MWE4YTNjOTlmYmM0NjYyMTc4NzgyMmNlYzM2YmQ4ODM1OWQwZGQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PwqUooVbq263Ds004s_o-fMt4QszYe3CSasvFJ-4NFU) ![image](https://private-user-images.githubusercontent.com/177441854/354877091-b57d9e49-ee2e-452a-ad8f-756176b32ddf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NDg1OTgsIm5iZiI6MTcyMjc0ODI5OCwicGF0aCI6Ii8xNzc0NDE4NTQvMzU0ODc3MDkxLWI1N2Q5ZTQ5LWVlMmUtNDUyYS1hZDhmLTc1NjE3NmIzMmRkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQwNTExMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGMyYWNkNjllOWY3MzZmOWZkMGJjZGY4M2UxNjY2NjlhZmFhNTU5MzRiODkyYTBkYTFjOGFlMGRiMjQ2YzU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oQlylWd3TkO6aGuQqNFt_HG6MIaQOJ66IOy5x7PB3nc) heres the proof im crimsonteam. yes i uploaded both mods to thunderstore so people dont take time to compile the github project and download stuff. i just made it so people can download it easily, and faster then compiling. im sorry if i made you mad or annoyed. i will not take credit for any mods i upload. i will link your kofi link in the upload later tomorrow or later midnight. once you upload fusion im deleting my upload. same with the mag perception upload i did.

You didn't even ask for Permission to upload any of this.
