### ISSUE TITLE
Void Door Idea [SUGGESTION]

### ISSUE THREAD

**Issue by KitchenBoy08** [Lakatrazz/BONELAB-Fusion#79]
Instead of Void Doors taking the user to another level (which is semi redundant IMHO) a user can drop a portal to any public lobby allowing all users from that server to join another public lobby together.

**Comment by Lakatrazz** [comment]
Why not an option between a preexisting lobby or a chosen level? There are a lot of cases where you'd want to go somewhere with someone but theres no existing lobbies for that scene

**Comment by Lakatrazz** [comment]
Also a portal instead of a void door allows for people to drop them on other people and removes any bonelab/slz theming

**Comment by KitchenBoy08** [comment]
I didnt mean to say portal lol, my bad
Also yeah having it be an option would be cool, probably easy too
Since on a lower level theyre the exact same thing, just joining a lobby when you enter a door
I just meant adding a button to each public lobby listing that allows you to drop a void door would be neat, rather than restricting it to lobbies you create

**Comment by Lakatrazz** [comment]
I see, yeah I'll make it an option

**Comment by KitchenBoy08** [comment]
Fire
