### ISSUE TITLE
not switching to spacewar active layer 

### ISSUE THREAD

**Issue by darrj** [Lakatrazz/BONELAB-Fusion#8]

**Comment by darrj** [comment]
it wount switch no matter how manny time i try

**Comment by DINOTICK-Dev** [comment]
BONELAB Fusion requires a restart in order to swap Networking Layers... Are you sure you closed and reopened BONELAB? Get back to me soon, thanks.
(Also FYI, most people use the Steam and Steam VR networking layers)

**Comment by Lakatrazz** [comment]
Fixed in 1.3.2
