### ISSUE TITLE
Player can easily see when blinded in Hide and Seek

### ISSUE THREAD

**Issue by spellboundtriangle** [Lakatrazz/BONELAB-Fusion#85]
If you shake your head during the countdown as a Seeker, it's pretty easy to see your surroundings. It's demonstrated in the video below, but you only see about half of it due to it only being a one eye recording.

https://github.com/user-attachments/assets/2868d01f-4527-41d7-993b-f44ab22d987d

**Comment by Lakatrazz** [comment]
Closing since duplicate of #86
