### ISSUE TITLE
Seeker blinding in Hide and Seek doesn't account for other avatar sizes

### ISSUE THREAD

**Issue by spellboundtriangle** [Lakatrazz/BONELAB-Fusion#86]
See below:
https://github.com/user-attachments/assets/d0bf6990-c7f7-4cd0-88fe-196a9cf44014

**Comment by Lakatrazz** [comment]
Fixed in https://github.com/Lakatrazz/BONELAB-Fusion/commit/bf5a95137db2790f19f0c0b8c88b025d651cf7f0
