### ISSUE TITLE
Missed a wide glasses have extreme offset

### ISSUE THREAD

**Issue by AdrianStillPlays** [Lakatrazz/BONELAB-Fusion#89]
ive been trying wear the glasses for it to not show and people don't see it either

**Comment by Lakatrazz** [comment]
Will investigate

**Comment by Lakatrazz** [comment]
Can now confirm it does show up, but its offset really far backwards

**Comment by DayTrip10** [comment]
I told lak a while ago and he told me it was a me problem

**Comment by AdrianStillPlays** [comment]
did you get it fixed yet?

**Comment by Lakatrazz** [comment]
Issue will be closed when it's fixed

**Comment by Lakatrazz** [comment]
Fixed in 2478bbf
