### ISSUE TITLE
I can feel EVERYTHING everyone else feels

### ISSUE THREAD

**Issue by C0deMasterYT** [Lakatrazz/BONELAB-Fusion#90]
In the new update for patch 5, specifically, I feel all the haptics that someone else feels, like firing a gun, picking something up, punching something, hitting something, etc. This didn't seem like too much of a problem, until I realized that this also happens with OWO Skin, with all the haptics transferring over to me. Every time my friend got shot, punched, stabbed, etc, I could feel ALL of it. In previous versions of Fusion, this wasn't an issue, everything worked fine, and I didn't feel anything my friends did, with both the base game's haptics and my OWO Skin haptics. I don't really know what changed between patch 3 Fusion and patch 5 fusion to cause this issue, but MAN it's terrifying to know that at any time, my friends (or other players in a public lobby) can just shoot themselves anywhere in the game and I'll feel it, lol.

**Comment by Lakatrazz** [comment]
I haven't had this happen except on certain modded guns (which add extra haptics that don't check for fusion), I assume you are using some kind of compatibility mod for owo skin which fusion does not support

**Comment by Lakatrazz** [comment]
I checked the mod source code and yeah, it basically overrides a lot of the game's haptics without checking if it's from another player, so for now you'll have to uninstall the owo haptic mod while in Fusion, and reinstall it if they end up adding compatibility for fusion
