### ISSUE TITLE
Dedicated Servers (Feature Request)

### ISSUE THREAD

**Issue by CoolPuppyKid** [Lakatrazz/BONELAB-Fusion#99]
I think it would be cool if you can host a dedicated server that also has plugins

**Comment by capybarajtmc** [comment]
Very good idea

**Comment by Lakatrazz** [comment]
This has been thought about before but will likely never happen due to the nature of it being a mod + the complexity of it being implemented
What's more likely is host migration (ex. when the host leaves another person becomes the server owner) but that will not happen for a long time either

**Comment by CoolPuppyKid** [comment]
> This has been thought about before but will likely never happen due to the nature of it being a mod + the complexity of it being implemented What's more likely is host migration (ex. when the host leaves another person becomes the server owner) but that will not happen for a long time either

alright
